# library(RODBC)
library(shiny)
library(data.table)
library(ggplot2)
library(reshape2)
library(forecast)
library(xlsx)
library(topicmodels)
# setwd("/var/shiny-server/www/LDAtwitter")
setwd("/Users/yuki/Documents/work\ sample/LDAtwitter")
load('dtm.new.RData')
load('df.RData')
load('rowTotals.RData')
